from datetime import datetime

from pydantic import BaseModel


class BriefingResponse(BaseModel):
    """Natural-language "State of the Sun" operator briefing.

    Generated by Claude from the dashboard's own current conditions, alerts,
    forecast, and event-chain storylines; regenerated (change-gated) by a
    scheduled pass and served from cache. ``available`` is False when no
    ``ANTHROPIC_API_KEY`` is configured, so the UI can hide the card gracefully.
    """
    text: str | None = None
    generated_at: datetime | None = None
    model: str | None = None
    available: bool = True
